#!/bin/bash
set -e

TYPE=$1
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ "$SCRIPT_DIR" != $(pwd) ]
then
  echo "You must run this script from $SCRIPT_DIR!"
  exit 1
fi

function copy_file() {
  FILE=$1
  DEST=$2
  if [ -f $HOME/$DEST ];
  then
    echo "$HOME/$DEST exists, creating a backup .bak file."
    cp -v $HOME/$DEST $HOME/$DEST.bak
  fi
  cp -v $FILE $HOME/$DEST
}

if [ "$TYPE" == "remote" ]
then
  copy_file ".vimrc_abridged" ".vimrc"
  copy_file ".bashrc_abridged" ".bash_profile"
else
  copy_file ".vimrc"
  copy_file ".bashrc"
fi

cp -Rv .vim/* ~/.vim
echo "Complete."
